- name: Install dependencies
  apt:
    name:
      - jq
      - gcc
    update_cache: true
    state: present
  become: true

- name: Create GitHub Actions user
  user:
    name: actions
    home: "/opt/actions-runner"
    create_home: true
    system: true
    comment: "GitHub Actions Runner"
    shell: "/bin/bash"
    groups: docker
    state: present
  become: true

- name: Download GitHub Actions Runner
  get_url:
    url: "https://github.com/actions/runner/releases/download/v2.286.1/actions-runner-linux-x64-2.286.1.tar.gz"
    dest: "/opt/actions-runner/actions-runner.tar.gz"
    checksum: sha256:7b1509c353ea4e6561b2ed2e916dcbf2a0d8ce21172edd9f8c846a20b6462cd6
  become: true
  become_user: actions

- name: Extract Runner
  unarchive:
    src: "/opt/actions-runner/actions-runner.tar.gz"
    dest: "/opt/actions-runner/"
    remote_src: true
  become: true
  become_user: actions

- name: Configure Runner
  shell: |
    mkdir /opt/actions-runner/work
    registration_url="https://api.github.com/orgs/otter-im/actions/runners/registration-token"
    payload=$(curl -sX POST -H "Authorization: token {{ github_token }}" ${registration_url})
    RUNNER_TOKEN=$(echo $payload | jq .token --raw-output)
    ./config.sh --url https://github.com/otter-im --token ${RUNNER_TOKEN} --unattended --replace --name $(hostname) --work /opt/actions-runner/work
  args:
    chdir: "/opt/actions-runner/"
  become: true
  become_user: actions

- name: Start Service
  shell: |
    ./svc.sh install
    sudo systemctl enable actions.runner.otter-im.$(hostname).service
    ./svc.sh start
  args:
    chdir: "/opt/actions-runner"
  become: true
