- name: Install Docker pre-requisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true
    state: present
  become: true

- name: Add Docker GPG Key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  become: true

- name: Add Docker Repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true

- name: Update apt cache
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true
  become: true

- name: Enable docker.service
  systemd:
    name: docker.service
    state: started
    enabled: true
  become: true

- name: Enable containerd.service
  systemd:
    name: containerd.service
    state: started
    enabled: true
  become: true
